resolver: lts-14.16
packages:
- domain-objects
- effects/clock
- effects/clock/handlers/io
- effects/clock/handlers/pure
- effects/io
- effects/talent-id-generator
- effects/talent-id-generator/handlers/pure
- effects/talent-id-generator/handlers/uuid-v4
- effects/talent-repository
- effects/talent-repository/handlers/io-ref
- effects/talent-repository/handlers/pure
- server
- use-cases
extra-deps:
- extensible-0.6.1@sha256:d73a5dc13bd00f44ace729f83ce868e81a45ea31c7453a6f8a4a9b5b0591d600,2860
- membership-0@sha256:3a11d8fd53cb1a76bb9273e6c929bbf9d649f109714bf487abb3143be04ddc81,995
