name:                effects-talent-id-generator-handlers-uuid-v4
version:             0
github:              "ryota-ka/domain-logic-on-eff"
license:             BSD3
author:              "Ryota Kameoka"
maintainer:          "kameoka.ryota@gmail.com"
copyright:           "2019 Ryota Kameoka"

dependencies:
- base
- domain-objects
- effects-io
- effects-talent-id-generator
- extensible
- uuid

ghc-options:
- -Wall
- -Werror

library:
  source-dirs: src
