name:                effects-clock
version:             0
github:              "ryota-ka/domain-logic-on-eff"
license:             BSD3
author:              "Ryota Kameoka"
maintainer:          "kameoka.ryota@gmail.com"
copyright:           "2019 Ryota Kameoka"

dependencies:
- base
- extensible
- time

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror
