name:                use-cases
version:             0
github:              "ryota-ka/domain-logic-on-eff"
license:             BSD3
author:              "Ryota Kameoka"
maintainer:          "kameoka.ryota@gmail.com"
copyright:           "2019 Ryota Kameoka"

dependencies:
- base
- domain-objects
- effects-clock
- effects-talent-id-generator
- effects-talent-repository
- extensible

ghc-options:
- -Wall
- -Werror

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - containers
    - effects-clock-handlers-pure
    - effects-talent-id-generator-handlers-pure
    - effects-talent-repository-handlers-pure
    - extensible
    - hspec
    - hspec-discover
    - time
    - use-cases
